### ISSUE TITLE
Generated cron expression is not valid

### ISSUE THREAD

**Issue by Karankang007** [angular-cron-jobs/angular-cron-jobs#24]
I am using the cron expression generated by your utility with Quartz scheduler and the validation fails because we are not specifying the year part.

Is it possible to add a configuration provider to angular-service so that user can optionally turn this on.

Changing
     ```var cron = ['*', '*', '*',  '*',  '*'];```
to 
     ```var cron = ['*', '*', '*',  '*',  '*', '*'];```
in service.setCron method of cronService fixes this issue.

**Comment by jacobscarter** [comment]
Yes, I will add this to the next release, hoping to get caught up and pushed out by Sunday.

Thanks!

**Comment by RajanRastogi** [comment]
I think there will be more changes required in order to get it to work with quartz scheduler. For example, day of week `1` represents sunday in quartz where as it represents monday in this current implementation.

**Comment by jacobscarter** [comment]
Looks like there is more to it then the additional item in the array.  I will close this issue until we see more request for Quartz support.

**Comment by RajanRastogi** [comment]
I actually needed this, so I have made another project based on this which generates cron expressions.

[https://github.com/RajanRastogi/angular-quartz-cron](angular-quartz-cron)

Since I was in a hurry, I could not support backward compatibility, hence could not raise a merge request. Have tried giving full credit to @jacobscarter.

**Comment by jacobscarter** [comment]
Glad you got something you can use! Well re open this if you ever decide to make it work with this report too :)

**Comment by vincent-zurczak** [comment]
Hi. :smiley: 

I wanted to thank you both for you work. :+1: 
I face the same issue with the generated expressions and Quartz. I tried the **angular-quartz-cron** and it works well. The only limit is that it does not support the **allowMultiple** option (which appeared with version 2.0). We can really regret there are two projects instead of one.

**Comment by jacobscarter** [comment]
That is in the works :)

**Comment by vincent-zurczak** [comment]
Hi. Any news about Quartz support?

**Comment by jacobscarter** [comment]
@vincent-zurczak I really need some help maintaining/updating this project. @RajanRastogi are you thinking you will have time soon to get quartz features merged into this project so the user can specify either to use quartz or not?

**Comment by vincent-zurczak** [comment]
Obviously, it would be better if @RajanRastogi could contribute what he did about Quartz support. Otherwise, I will try to contribute myself, as we really need this feature for our project.

**Comment by jacobscarter** [comment]
@vincent-zurczak let me know if you have any questions and I can review whatever code you submit.  Thanks.

**Comment by RajanRastogi** [comment]
@jacobscarter I can, but my approach is sort of dirty. I'll submit a PR, would love to get feedback on it.

**Comment by jacobscarter** [comment]
Being addressed in PR #54

**Comment by vincent-zurczak** [comment]
So great! :tada: 
Thanks guys! :+1:

**Comment by jacobscarter** [comment]
Available in 3.2.0

**Comment by jacobscarter** [comment]
Thanks to @RajanRastogi 

https://github.com/angular-cron-jobs/angular-cron-jobs/blob/master/README.md#quartz-by-rajanrastogi
